/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import biblioteca.Biblioteca;
import biblioteca.BuscaFalhouException;
import biblioteca.ItemAcervo;
import biblioteca.Livro;
import biblioteca.Periodico;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Karlla
 */
public class JFCancelaReserva extends javax.swing.JFrame {

    private TelaPrincipal telaPrincipal;
    private Biblioteca biblioteca;
    private ItemAcervo item;
    
    DefaultTableModel tmLivro = new DefaultTableModel(null, new String[]{"Nome", "Autor", "Situação"});
    
    /**
     * Creates new form JFCancelaReserva
     */
    public JFCancelaReserva() {
        initComponents();
    }
    
    public JFCancelaReserva(TelaPrincipal telaPrincipal, Biblioteca b) {
        this();
        
        this.telaPrincipal = telaPrincipal;
        this.biblioteca = b;
        jBConfirma.setEnabled(false);
        jTFNome.setEditable(false);
        jTFLivro.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jBPesquisarLivro = new javax.swing.JButton();
        jTFLivroPesquisa = new javax.swing.JTextField();
        jRBTitulo = new javax.swing.JRadioButton();
        jRBPeriodico = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBConfirma = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTFLivro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Item"));

        jBPesquisarLivro.setText("Pesquisar");
        jBPesquisarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarLivroActionPerformed(evt);
            }
        });

        jTFLivroPesquisa.setName("jTFLivroPesquisa"); // NOI18N
        jTFLivroPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFLivroPesquisaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBTitulo);
        jRBTitulo.setText("Livro");
        jRBTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTituloActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBPeriodico);
        jRBPeriodico.setText("Periodico");
        jRBPeriodico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPeriodicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jRBTitulo)
                .addGap(18, 18, 18)
                .addComponent(jRBPeriodico)
                .addGap(27, 27, 27)
                .addComponent(jTFLivroPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBPesquisarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBTitulo)
                    .addComponent(jRBPeriodico)
                    .addComponent(jTFLivroPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisarLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jTable1.setModel(tmLivro);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Selecione o ítem  para o qual deseja cancelar a reserva:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBConfirma.setText("Cancelar Reserva");
        jBConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConfirmaActionPerformed(evt);
            }
        });

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBConfirma, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jBConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Reserva"));

        jLabel2.setText("Livro / Periódico:");

        jTFLivro.setBackground(new java.awt.Color(255, 255, 255));
        jTFLivro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTFLivro.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setText("> Cliente");

        jLabel5.setText("Nome:");

        jTFNome.setBackground(new java.awt.Color(255, 255, 255));
        jTFNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTFNome.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFNome)
                            .addComponent(jTFLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarLivroActionPerformed

        item = null;
        jTFLivro.setText("");
        jTFNome.setText("");
        jBConfirma.setEnabled(false);

        ArrayList<Livro> livros = new ArrayList<>();
        ArrayList<Periodico> periodico = new ArrayList<>();

        String texto = jTFLivroPesquisa.getText();

        if(texto.equals("")){
            JOptionPane.showMessageDialog(null, "Digite o título!", "Error", JOptionPane.ERROR_MESSAGE);
            jTFLivro.setText("");
        } else if(!jRBPeriodico.isSelected() && !jRBTitulo.isSelected()){
            JOptionPane.showMessageDialog(null, "Selecione o tipo de busca (Livro ou Periódico)!", "Error", JOptionPane.ERROR_MESSAGE);
            jTFLivro.setText("");
        } else{

            if(jRBPeriodico.isSelected()){
                periodico = biblioteca.listarPeriodicosNome(texto);

                if(periodico.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Nenhum registro encontrado!", "Error", JOptionPane.ERROR_MESSAGE);
                    jTFLivro.setText("");
                } else {
                    limparTabela();

                    String[] linha = new String[] {null, null, null};
                    for (int i = 0; i < periodico.size(); i++) {
                        tmLivro.addRow(linha);
                        tmLivro.setValueAt(periodico.get(i).getTitulo(), i, 0);
                        tmLivro.setValueAt(periodico.get(i).getEditora(), i, 1);
                        if(periodico.get(i).isDisponivel()){
                            tmLivro.setValueAt("Disponível", i, 2);
                        } else {
                            tmLivro.setValueAt("Indisponível", i, 2);
                        }
                    }
                }

            } else {
                livros = biblioteca.listarLivrosNome(texto);

                if(livros.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Nenhum registro encontrado!", "Error", JOptionPane.ERROR_MESSAGE);
                    jTFLivro.setText("");
                } else {
                    limparTabela();

                    String[] linha = new String[] {null, null, null};
                    // P/ cada registro é criada uma nova linha, cada linha recebe os campos do registro
                    for (int i = 0; i < livros.size(); i++) {

                        tmLivro.addRow(linha);
                        tmLivro.setValueAt(livros.get(i).getTitulo(), i, 0);
                        tmLivro.setValueAt(livros.get(i).getAutor(), i, 1);
                        if(livros.get(i).isDisponivel()){
                            tmLivro.setValueAt("Disponível", i, 2);
                        } else {
                            tmLivro.setValueAt("Indisponível", i, 2);
                        }
                    }
                }
            }
        }

        jTFLivroPesquisa.setText("");
    }//GEN-LAST:event_jBPesquisarLivroActionPerformed

    private void jTFLivroPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFLivroPesquisaActionPerformed
        // TODO add your handling code here:
        System.out.println("CLicou!!!");
    }//GEN-LAST:event_jTFLivroPesquisaActionPerformed

    private void jRBTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBTituloActionPerformed

    private void jRBPeriodicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPeriodicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBPeriodicoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = jTable1.getSelectedRow();

        try{
            //procurando pelo objeto com nome exato
            item = biblioteca.procurarItem((String)jTable1.getValueAt(linhaSelecionada, 0));

            if(!item.isReservado()){
                JOptionPane.showMessageDialog(null, "O Livro/Periódico não possui reservas!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                jTFLivro.setText(item.getTitulo());
                jTFNome.setText(item.getReserva().getCliente().getNome());
                jBConfirma.setEnabled(true);
            }
        } catch (BuscaFalhouException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.INFORMATION_MESSAGE);
            jTFLivro.setText("");
            jBConfirma.setEnabled(false);
            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        telaPrincipal.setEnabled(true);
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConfirmaActionPerformed
        // TODO add your handling code here:
        if(item != null){
            item.setReservado(false);
            item.setReserva(null);
            
            JOptionPane.showMessageDialog(null, "Reserva do ítem/Periódico cancelada com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            
            item = null;
            jTFLivro.setText("");
            jTFNome.setText("");
            jBConfirma.setEnabled(false);
            limparTabela();

        } else {
            JOptionPane.showMessageDialog(null, "Falha ao cancelar reserva!", "Falha", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBConfirmaActionPerformed

    private void limparTabela() {       
        while (tmLivro.getRowCount() > 0) {            
            tmLivro.removeRow(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCancelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCancelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCancelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCancelaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCancelaReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBConfirma;
    private javax.swing.JButton jBPesquisarLivro;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRBPeriodico;
    private javax.swing.JRadioButton jRBTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFLivro;
    private javax.swing.JTextField jTFLivroPesquisa;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
