
package frames;

import biblioteca.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Month;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karll
 */
public class JFCriaEmprestimo extends javax.swing.JFrame {

    private TelaPrincipal telaPrincipal;
    private Biblioteca biblioteca;
    private Cliente cliente;
    private ItemAcervo item;
    
    DefaultTableModel tmLivro = new DefaultTableModel(null, new String[]{"Nome", "Autor", "Situação"});
    /**
     * Creates new form JFCriaEmprestimo
     */
    public JFCriaEmprestimo() {
        initComponents();
    }

    public JFCriaEmprestimo(TelaPrincipal telaPrincipal, Biblioteca b) {
        this();
        
        this.telaPrincipal = telaPrincipal;
        this.biblioteca = b;
        jTFNome.setEditable(false);
        jTFCpf.setEditable(false);
        jTFLivro.setEditable(false);
        jBReservar.setEnabled(false);
        jBEmprestar.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jBPesquisarLivro = new javax.swing.JButton();
        jTFLivroPesquisa = new javax.swing.JTextField();
        jRBTitulo = new javax.swing.JRadioButton();
        jRBPeriodico = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBPesquisarCliente = new javax.swing.JButton();
        jTFCpfPesquisa = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTFLivro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFCpf = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jBEmprestar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBSair = new javax.swing.JButton();
        jBReservar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFDia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFMes = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFAno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Item"));

        jBPesquisarLivro.setText("Pesquisar");
        jBPesquisarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarLivroActionPerformed(evt);
            }
        });

        jTFLivroPesquisa.setName("jTFLivroPesquisa"); // NOI18N
        jTFLivroPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFLivroPesquisaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBTitulo);
        jRBTitulo.setText("Livro");
        jRBTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBTituloActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRBPeriodico);
        jRBPeriodico.setText("Periodico");
        jRBPeriodico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPeriodicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jRBTitulo)
                .addGap(18, 18, 18)
                .addComponent(jRBPeriodico)
                .addGap(27, 27, 27)
                .addComponent(jTFLivroPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBPesquisarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBTitulo)
                    .addComponent(jRBPeriodico)
                    .addComponent(jTFLivroPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisarLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jTable1.setModel(tmLivro);
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Cliente"));

        jLabel1.setText("C.P.F.");

        jBPesquisarCliente.setText("Pesquisar");
        jBPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarClienteActionPerformed(evt);
            }
        });

        jTFCpfPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFCpfPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTFCpfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFCpfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Empréstimo"));

        jTFLivro.setBackground(new java.awt.Color(255, 255, 255));
        jTFLivro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTFLivro.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setText("> Cliente");

        jLabel4.setText("Livro / Periódico:");

        jLabel5.setText("Nome:");

        jLabel9.setText("CPF:");

        jTFNome.setBackground(new java.awt.Color(255, 255, 255));
        jTFNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTFNome.setForeground(new java.awt.Color(0, 0, 0));

        jTFCpf.setBackground(new java.awt.Color(255, 255, 255));
        jTFCpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTFCpf.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(291, 291, 291)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jTFLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBEmprestar.setText("Emprestar");
        jBEmprestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEmprestarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBSair.setText("Sair");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });

        jBReservar.setText("Reservar");
        jBReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReservarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBEmprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jBEmprestar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jBReservar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jBCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jBSair, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jLabel2.setText("Data de realização do empréstimo / reserva:");

        jLabel8.setText("Dia:");

        jLabel10.setText("Mês:");

        jTFMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFMesActionPerformed(evt);
            }
        });

        jLabel11.setText("Ano:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFDia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFMes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFAno, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTFDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTFMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTFAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarLivroActionPerformed

        //jBNovo.setEnabled(false);
        jTFLivro.setText("");
        //desabilitaCampos();

        ArrayList<Livro> livros = new ArrayList<>();
        ArrayList<Periodico> periodico = new ArrayList<>();

        String texto = jTFLivroPesquisa.getText();

        if(texto.equals("")){
            JOptionPane.showMessageDialog(null, "Digite o título!", "Error", JOptionPane.ERROR_MESSAGE);
            jTFLivro.setText("");
        } else if(!jRBPeriodico.isSelected() && !jRBTitulo.isSelected()){
            JOptionPane.showMessageDialog(null, "Selecione o tipo de busca (Livro ou Periódico)!", "Error", JOptionPane.ERROR_MESSAGE);
            jTFLivro.setText("");
        } else{
            
            if(jRBPeriodico.isSelected()){
                periodico = biblioteca.listarPeriodicosNome(texto);
                
                if(periodico.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Nenhum registro encontrado!", "Error", JOptionPane.ERROR_MESSAGE);
                    jTFLivro.setText("");
                } else {
                    limparTabela();
                    //tmLivro = new DefaultTableModel(null, new String[]{"Nome", "Editora", "Situação"});
                    String[] linha = new String[] {null, null, null};
                    for (int i = 0; i < livros.size(); i++) {
                        tmLivro.addRow(linha);
                        tmLivro.setValueAt(periodico.get(i).getTitulo(), i, 0);
                        tmLivro.setValueAt(periodico.get(i).getEditora(), i, 1);
                        if(periodico.get(i).isDisponivel()){
                            tmLivro.setValueAt("Disponível", i, 2);
                        } else {
                            tmLivro.setValueAt("Indisponível", i, 2);
                        }
                    }
                }
                
            } else {
                livros = biblioteca.listarLivrosNome(texto);
                
                if(livros.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Nenhum registro encontrado!", "Error", JOptionPane.ERROR_MESSAGE);
                    jTFLivro.setText("");
                } else {
                    limparTabela();
                    //tmLivro = new DefaultTableModel(null, new String[]{"Nome", "Autor", "Situação"});
                    String[] linha = new String[] {null, null, null};
                    // P/ cada registro é criada uma nova linha, cada linha recebe os campos do registro
                    for (int i = 0; i < livros.size(); i++) {

                        tmLivro.addRow(linha);
                        tmLivro.setValueAt(livros.get(i).getTitulo(), i, 0);
                        tmLivro.setValueAt(livros.get(i).getAutor(), i, 1);
                        if(livros.get(i).isDisponivel()){
                            tmLivro.setValueAt("Disponível", i, 2);
                        } else {
                            tmLivro.setValueAt("Indisponível", i, 2);
                        }
                    }
                }
            }
        }

        jTFLivroPesquisa.setText("");
    }//GEN-LAST:event_jBPesquisarLivroActionPerformed

    private void jTFLivroPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFLivroPesquisaActionPerformed
        // TODO add your handling code here:
        System.out.println("CLicou!!!");
    }//GEN-LAST:event_jTFLivroPesquisaActionPerformed

    private void jRBTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBTituloActionPerformed

    private void jRBPeriodicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPeriodicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBPeriodicoActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = jTable1.getSelectedRow();
        //desabilitaCampos();

        try{
            //procurando pelo objeto com nome exato
            item = biblioteca.procurarItem((String)jTable1.getValueAt(linhaSelecionada, 0));
            
            jTFLivro.setText(item.getTitulo());
            
            if(item.isDisponivel()){
                jBEmprestar.setEnabled(true);
                jBReservar.setEnabled(false);
            } else {
                jBReservar.setEnabled(true);
                jBEmprestar.setEnabled(false);
            }
            
        } catch (BuscaFalhouException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.INFORMATION_MESSAGE);
            jTFLivro.setText("");
            //limpaCampos();
            //limparSituacao();
            //jBAlterar.setEnabled(false);
            //jBExcluir.setEnabled(false);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jBPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarClienteActionPerformed


        String cpf = (jTFCpfPesquisa.getText());

        if(cpf.equals("")){
            JOptionPane.showMessageDialog(null, "Insira o número do CPF!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try{
                cliente = biblioteca.procurarCliente(cpf);
                exibeCliente(cliente);
            } catch (BuscaFalhouException e){
                JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.INFORMATION_MESSAGE);
                jTFNome.setText("");
                jTFCpf.setText("");
            }
        }

        jTFCpfPesquisa.setText("");
    }//GEN-LAST:event_jBPesquisarClienteActionPerformed

    private void jTFCpfPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFCpfPesquisaActionPerformed
        // TODO add your handling code here:
        System.out.println("CLicou!!!");
    }//GEN-LAST:event_jTFCpfPesquisaActionPerformed

    private void jTFMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFMesActionPerformed

    private void jBEmprestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEmprestarActionPerformed
        // TODO add your handling code here:
        
        LocalDate ld = null;
        boolean ok = true;
        
        if(jTFLivro.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Necessário selecionar o Livro/Periódico para realizar o empréstimo!", "Error", JOptionPane.ERROR_MESSAGE);
            ok = false;
        } 
        if(jTFNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Necessário informar o cliente para realizar o empréstimo!", "Error", JOptionPane.ERROR_MESSAGE);
            ok = false;
        } 
        if(jTFDia.getText().equals("") || jTFMes.getText().equals("") || jTFAno.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe a data!", "Error", JOptionPane.ERROR_MESSAGE);
            ok = false;
        } else {
            int dia = Integer.parseInt(jTFDia.getText());
            int mes = Integer.parseInt(jTFMes.getText());
            int ano = Integer.parseInt(jTFAno.getText());
        
            ld = LocalDate.of(ano, mes, dia);
        }

        //pode validar a data aqui
        
        if(ok){
          
            try{
                
                Emprestimo emp = cliente.realizarEmprestimo(item, ld);
                biblioteca.addHistoricoEmprestimos(emp);
                
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

                
                String mensagem = "Empréstimo realizado! \n"
                        + "Cliente: " + cliente.getNome() + "\n" 
                        + "Livro/Periódico: " + item.getTitulo() + "\n"
                        + "Data do empréstimo: " + ld.format(formatter) + "\n\n"
                        + "Data para devolução do empréstimo: " + emp.getDataDevolucaoPrevista().format(formatter);
                
                
                JOptionPane.showMessageDialog(null, mensagem, "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                
                limparTabela();
                jBEmprestar.setEnabled(false);
                limparCampos();
                
            } catch (ItemIndisponivelException | ClienteComPendenciaException e){
                JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_jBEmprestarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
        
        jBReservar.setEnabled(false);
        jBEmprestar.setEnabled(false);
        jTFNome.setText("");
        jTFCpf.setText("");
        jTFLivro.setText("");
        jTFAno.setText("");
        jTFDia.setText("");
        jTFMes.setText("");
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBSairActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        telaPrincipal.setEnabled(true);
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jBReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReservarActionPerformed
        
        LocalDate ld = null;
        boolean ok = true;
        
        if(jTFNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Necessário informar o cliente para realizar o empréstimo!", "Error", JOptionPane.ERROR_MESSAGE);
            ok = false;
        }
        if(jTFDia.getText().equals("") || jTFMes.getText().equals("") || jTFAno.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe a data!", "Error", JOptionPane.ERROR_MESSAGE);
            ok = false;
        } else {
            int dia = Integer.parseInt(jTFDia.getText());
            int mes = Integer.parseInt(jTFMes.getText());
            int ano = Integer.parseInt(jTFAno.getText());
        
            ld = LocalDate.of(ano, mes, dia);
        }
        if(ok){
            try{

                    if(item.registrarReserva(cliente, ld)){
                        String mensagem = "A reserva do livro/periódico \n"
                                + item.getTitulo() + " foi realizada com sucesso\n"
                                + "para " + cliente.getNome() + "\n";
                        JOptionPane.showMessageDialog(null, mensagem, "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                        limparTabela();
                        jBReservar.setEnabled(false);
                        limparCampos();

                    } else {
                        JOptionPane.showMessageDialog(null, "O livro já está reservado!", "Falha", JOptionPane.INFORMATION_MESSAGE);
                    }

            } catch(ClienteComPendenciaException e){
                JOptionPane.showMessageDialog(null, e.getMessage(), "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jBReservarActionPerformed

    public void exibeCliente(Cliente c){
        jTFNome.setText(c.getNome());
        jTFCpf.setText(c.getCpf());
    }
    
    // Limpa a tabela de resultados
    private void limparTabela() {       
        while (tmLivro.getRowCount() > 0) {            
            tmLivro.removeRow(0);
        }
    }
    
    private void limparCampos(){
        jTFNome.setText("");
        jTFCpf.setText("");
        jTFLivro.setText("");
        jTFDia.setText("");
        jTFMes.setText("");
        jTFAno.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCriaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCriaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCriaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCriaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCriaEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEmprestar;
    private javax.swing.JButton jBPesquisarCliente;
    private javax.swing.JButton jBPesquisarLivro;
    private javax.swing.JButton jBReservar;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRBPeriodico;
    private javax.swing.JRadioButton jRBTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFAno;
    private javax.swing.JTextField jTFCpf;
    private javax.swing.JTextField jTFCpfPesquisa;
    private javax.swing.JTextField jTFDia;
    private javax.swing.JTextField jTFLivro;
    private javax.swing.JTextField jTFLivroPesquisa;
    private javax.swing.JTextField jTFMes;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
